// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: candles.sql

package db

import (
	"context"
	"database/sql"
)

const createCandles = `-- name: CreateCandles :execresult
INSERT INTO robot.candles (
  uid,
  date,
  open,
  close,
  high,
  low,
  volume
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

func (q *Queries) CreateCandles(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCandles)
}
