// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type RobotCandle struct {
	Uid    string
	Date   time.Time
	Open   float64
	Close  float64
	High   float64
	Low    float64
	Volume sql.NullInt32
}
