// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: candles.sql

package db

import (
	"time"
)

type CreateCandlesParams struct {
	UID    string
	Date   time.Time
	Open   float32
	Close  float32
	High   float32
	Low    float32
	Volume int64
}
