// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateCandles(ctx context.Context, arg []CreateCandlesParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
