// Code generated by ogen, DO NOT EDIT.
package ogen

type InstrumentsServiceBondByRes interface {
	instrumentsServiceBondByRes()
}

type InstrumentsServiceBondsRes interface {
	instrumentsServiceBondsRes()
}

type InstrumentsServiceCurrenciesRes interface {
	instrumentsServiceCurrenciesRes()
}

type InstrumentsServiceCurrencyByRes interface {
	instrumentsServiceCurrencyByRes()
}

type InstrumentsServiceEditFavoritesRes interface {
	instrumentsServiceEditFavoritesRes()
}

type InstrumentsServiceEtfByRes interface {
	instrumentsServiceEtfByRes()
}

type InstrumentsServiceEtfsRes interface {
	instrumentsServiceEtfsRes()
}

type InstrumentsServiceFindInstrumentRes interface {
	instrumentsServiceFindInstrumentRes()
}

type InstrumentsServiceFutureByRes interface {
	instrumentsServiceFutureByRes()
}

type InstrumentsServiceFuturesRes interface {
	instrumentsServiceFuturesRes()
}

type InstrumentsServiceGetAccruedInterestsRes interface {
	instrumentsServiceGetAccruedInterestsRes()
}

type InstrumentsServiceGetAssetByRes interface {
	instrumentsServiceGetAssetByRes()
}

type InstrumentsServiceGetAssetsRes interface {
	instrumentsServiceGetAssetsRes()
}

type InstrumentsServiceGetBondCouponsRes interface {
	instrumentsServiceGetBondCouponsRes()
}

type InstrumentsServiceGetBrandByRes interface {
	instrumentsServiceGetBrandByRes()
}

type InstrumentsServiceGetBrandsRes interface {
	instrumentsServiceGetBrandsRes()
}

type InstrumentsServiceGetCountriesRes interface {
	instrumentsServiceGetCountriesRes()
}

type InstrumentsServiceGetDividendsRes interface {
	instrumentsServiceGetDividendsRes()
}

type InstrumentsServiceGetFavoritesRes interface {
	instrumentsServiceGetFavoritesRes()
}

type InstrumentsServiceGetFuturesMarginRes interface {
	instrumentsServiceGetFuturesMarginRes()
}

type InstrumentsServiceGetInstrumentByRes interface {
	instrumentsServiceGetInstrumentByRes()
}

type InstrumentsServiceOptionByRes interface {
	instrumentsServiceOptionByRes()
}

type InstrumentsServiceOptionsRes interface {
	instrumentsServiceOptionsRes()
}

type InstrumentsServiceShareByRes interface {
	instrumentsServiceShareByRes()
}

type InstrumentsServiceSharesRes interface {
	instrumentsServiceSharesRes()
}

type InstrumentsServiceTradingSchedulesRes interface {
	instrumentsServiceTradingSchedulesRes()
}

type MarketDataServiceGetCandlesRes interface {
	marketDataServiceGetCandlesRes()
}

type MarketDataServiceGetClosePricesRes interface {
	marketDataServiceGetClosePricesRes()
}

type MarketDataServiceGetLastPricesRes interface {
	marketDataServiceGetLastPricesRes()
}

type MarketDataServiceGetLastTradesRes interface {
	marketDataServiceGetLastTradesRes()
}

type MarketDataServiceGetOrderBookRes interface {
	marketDataServiceGetOrderBookRes()
}

type MarketDataServiceGetTradingStatusRes interface {
	marketDataServiceGetTradingStatusRes()
}

type MarketDataServiceGetTradingStatusesRes interface {
	marketDataServiceGetTradingStatusesRes()
}

type OperationsServiceGetBrokerReportRes interface {
	operationsServiceGetBrokerReportRes()
}

type OperationsServiceGetDividendsForeignIssuerRes interface {
	operationsServiceGetDividendsForeignIssuerRes()
}

type OperationsServiceGetOperationsByCursorRes interface {
	operationsServiceGetOperationsByCursorRes()
}

type OperationsServiceGetOperationsRes interface {
	operationsServiceGetOperationsRes()
}

type OperationsServiceGetPortfolioRes interface {
	operationsServiceGetPortfolioRes()
}

type OperationsServiceGetPositionsRes interface {
	operationsServiceGetPositionsRes()
}

type OperationsServiceGetWithdrawLimitsRes interface {
	operationsServiceGetWithdrawLimitsRes()
}

type OrdersServiceCancelOrderRes interface {
	ordersServiceCancelOrderRes()
}

type OrdersServiceGetOrderStateRes interface {
	ordersServiceGetOrderStateRes()
}

type OrdersServiceGetOrdersRes interface {
	ordersServiceGetOrdersRes()
}

type OrdersServicePostOrderRes interface {
	ordersServicePostOrderRes()
}

type OrdersServiceReplaceOrderRes interface {
	ordersServiceReplaceOrderRes()
}

type SandboxServiceCancelSandboxOrderRes interface {
	sandboxServiceCancelSandboxOrderRes()
}

type SandboxServiceCloseSandboxAccountRes interface {
	sandboxServiceCloseSandboxAccountRes()
}

type SandboxServiceGetSandboxAccountsRes interface {
	sandboxServiceGetSandboxAccountsRes()
}

type SandboxServiceGetSandboxOperationsByCursorRes interface {
	sandboxServiceGetSandboxOperationsByCursorRes()
}

type SandboxServiceGetSandboxOperationsRes interface {
	sandboxServiceGetSandboxOperationsRes()
}

type SandboxServiceGetSandboxOrderStateRes interface {
	sandboxServiceGetSandboxOrderStateRes()
}

type SandboxServiceGetSandboxOrdersRes interface {
	sandboxServiceGetSandboxOrdersRes()
}

type SandboxServiceGetSandboxPortfolioRes interface {
	sandboxServiceGetSandboxPortfolioRes()
}

type SandboxServiceGetSandboxPositionsRes interface {
	sandboxServiceGetSandboxPositionsRes()
}

type SandboxServiceGetSandboxWithdrawLimitsRes interface {
	sandboxServiceGetSandboxWithdrawLimitsRes()
}

type SandboxServiceOpenSandboxAccountRes interface {
	sandboxServiceOpenSandboxAccountRes()
}

type SandboxServicePostSandboxOrderRes interface {
	sandboxServicePostSandboxOrderRes()
}

type SandboxServiceReplaceSandboxOrderRes interface {
	sandboxServiceReplaceSandboxOrderRes()
}

type SandboxServiceSandboxPayInRes interface {
	sandboxServiceSandboxPayInRes()
}

type StopOrdersServiceCancelStopOrderRes interface {
	stopOrdersServiceCancelStopOrderRes()
}

type StopOrdersServiceGetStopOrdersRes interface {
	stopOrdersServiceGetStopOrdersRes()
}

type StopOrdersServicePostStopOrderRes interface {
	stopOrdersServicePostStopOrderRes()
}

type UsersServiceGetAccountsRes interface {
	usersServiceGetAccountsRes()
}

type UsersServiceGetInfoRes interface {
	usersServiceGetInfoRes()
}

type UsersServiceGetMarginAttributesRes interface {
	usersServiceGetMarginAttributesRes()
}

type UsersServiceGetUserTariffRes interface {
	usersServiceGetUserTariffRes()
}
