// Code generated by ogen, DO NOT EDIT.

package ogen

// setDefaults set default value of fields.
func (s *V1Account) setDefaults() {
	{
		val := V1AccountType("ACCOUNT_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
	{
		val := V1AccountStatus("ACCOUNT_STATUS_UNSPECIFIED")
		s.Status.SetTo(val)
	}
	{
		val := V1AccessLevel("ACCOUNT_ACCESS_LEVEL_UNSPECIFIED")
		s.AccessLevel.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Asset) setDefaults() {
	{
		val := V1AssetType("ASSET_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1AssetFull) setDefaults() {
	{
		val := V1AssetType("ASSET_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1AssetInstrument) setDefaults() {
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1AssetSecurity) setDefaults() {
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1AssetShare) setDefaults() {
	{
		val := V1ShareType("SHARE_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1AssetStructuredProduct) setDefaults() {
	{
		val := V1StructuredProductType("SP_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
	{
		val := V1AssetType("ASSET_TYPE_UNSPECIFIED")
		s.AssetType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Bond) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
	{
		val := V1RiskLevel("RISK_LEVEL_UNSPECIFIED")
		s.RiskLevel.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Coupon) setDefaults() {
	{
		val := V1CouponType("COUPON_TYPE_UNSPECIFIED")
		s.CouponType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Currency) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1EditFavoritesRequest) setDefaults() {
	{
		val := V1EditFavoritesActionType("EDIT_FAVORITES_ACTION_TYPE_UNSPECIFIED")
		s.ActionType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Etf) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1FavoriteInstrument) setDefaults() {
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Future) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1GetCandlesRequest) setDefaults() {
	{
		val := V1CandleInterval("CANDLE_INTERVAL_UNSPECIFIED")
		s.Interval.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1GetOperationsByCursorRequest) setDefaults() {
	{
		val := V1OperationState("OPERATION_STATE_UNSPECIFIED")
		s.State.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1GetTradingStatusResponse) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Instrument) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1InstrumentRequest) setDefaults() {
	{
		val := V1InstrumentIdType("INSTRUMENT_ID_UNSPECIFIED")
		s.IdType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1InstrumentShort) setDefaults() {
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1InstrumentsRequest) setDefaults() {
	{
		val := V1InstrumentStatus("INSTRUMENT_STATUS_UNSPECIFIED")
		s.InstrumentStatus.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Operation) setDefaults() {
	{
		val := V1OperationState("OPERATION_STATE_UNSPECIFIED")
		s.State.SetTo(val)
	}
	{
		val := V1OperationType("OPERATION_TYPE_UNSPECIFIED")
		s.OperationType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1OperationItem) setDefaults() {
	{
		val := V1OperationType("OPERATION_TYPE_UNSPECIFIED")
		s.Type.SetTo(val)
	}
	{
		val := V1OperationState("OPERATION_STATE_UNSPECIFIED")
		s.State.SetTo(val)
	}
	{
		val := V1InstrumentType("INSTRUMENT_TYPE_UNSPECIFIED")
		s.InstrumentKind.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1OperationsRequest) setDefaults() {
	{
		val := V1OperationState("OPERATION_STATE_UNSPECIFIED")
		s.State.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Option) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
	{
		val := V1OptionDirection("OPTION_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1OptionPaymentType("OPTION_PAYMENT_TYPE_UNSPECIFIED")
		s.PaymentType.SetTo(val)
	}
	{
		val := V1OptionStyle("OPTION_STYLE_UNSPECIFIED")
		s.Style.SetTo(val)
	}
	{
		val := V1OptionSettlementType("OPTION_EXECUTION_TYPE_UNSPECIFIED")
		s.SettlementType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1OrderState) setDefaults() {
	{
		val := V1OrderExecutionReportStatus("EXECUTION_REPORT_STATUS_UNSPECIFIED")
		s.ExecutionReportStatus.SetTo(val)
	}
	{
		val := V1OrderDirection("ORDER_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1OrderType("ORDER_TYPE_UNSPECIFIED")
		s.OrderType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1PortfolioRequest) setDefaults() {
	{
		val := PortfolioRequestCurrencyRequest("RUB")
		s.Currency.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1PostOrderRequest) setDefaults() {
	{
		val := V1OrderDirection("ORDER_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1OrderType("ORDER_TYPE_UNSPECIFIED")
		s.OrderType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1PostOrderResponse) setDefaults() {
	{
		val := V1OrderExecutionReportStatus("EXECUTION_REPORT_STATUS_UNSPECIFIED")
		s.ExecutionReportStatus.SetTo(val)
	}
	{
		val := V1OrderDirection("ORDER_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1OrderType("ORDER_TYPE_UNSPECIFIED")
		s.OrderType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1PostStopOrderRequest) setDefaults() {
	{
		val := V1StopOrderDirection("STOP_ORDER_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1StopOrderExpirationType("STOP_ORDER_EXPIRATION_TYPE_UNSPECIFIED")
		s.ExpirationType.SetTo(val)
	}
	{
		val := V1StopOrderType("STOP_ORDER_TYPE_UNSPECIFIED")
		s.StopOrderType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1ReplaceOrderRequest) setDefaults() {
	{
		val := V1PriceType("PRICE_TYPE_UNSPECIFIED")
		s.PriceType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Share) setDefaults() {
	{
		val := V1SecurityTradingStatus("SECURITY_TRADING_STATUS_UNSPECIFIED")
		s.TradingStatus.SetTo(val)
	}
	{
		val := V1ShareType("SHARE_TYPE_UNSPECIFIED")
		s.ShareType.SetTo(val)
	}
	{
		val := V1RealExchange("REAL_EXCHANGE_UNSPECIFIED")
		s.RealExchange.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1StopOrder) setDefaults() {
	{
		val := V1StopOrderDirection("STOP_ORDER_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
	{
		val := V1StopOrderType("STOP_ORDER_TYPE_UNSPECIFIED")
		s.OrderType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *V1Trade) setDefaults() {
	{
		val := V1TradeDirection("TRADE_DIRECTION_UNSPECIFIED")
		s.Direction.SetTo(val)
	}
}
