// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// InstrumentsServiceBondBy implements InstrumentsService_BondBy operation.
	//
	// Метод получения облигации по её идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/BondBy
	InstrumentsServiceBondBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceBondByRes, error)
	// InstrumentsServiceBonds implements InstrumentsService_Bonds operation.
	//
	// Метод получения списка облигаций.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Bonds
	InstrumentsServiceBonds(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceBondsRes, error)
	// InstrumentsServiceCurrencies implements InstrumentsService_Currencies operation.
	//
	// Метод получения списка валют.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Currencies
	InstrumentsServiceCurrencies(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceCurrenciesRes, error)
	// InstrumentsServiceCurrencyBy implements InstrumentsService_CurrencyBy operation.
	//
	// Метод получения валюты по её идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/CurrencyBy
	InstrumentsServiceCurrencyBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceCurrencyByRes, error)
	// InstrumentsServiceEditFavorites implements InstrumentsService_EditFavorites operation.
	//
	// Метод редактирования списка избранных инструментов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/EditFavorites
	InstrumentsServiceEditFavorites(ctx context.Context, req *V1EditFavoritesRequest) (InstrumentsServiceEditFavoritesRes, error)
	// InstrumentsServiceEtfBy implements InstrumentsService_EtfBy operation.
	//
	// Метод получения инвестиционного фонда по его
	// идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/EtfBy
	InstrumentsServiceEtfBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceEtfByRes, error)
	// InstrumentsServiceEtfs implements InstrumentsService_Etfs operation.
	//
	// Метод получения списка инвестиционных фондов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Etfs
	InstrumentsServiceEtfs(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceEtfsRes, error)
	// InstrumentsServiceFindInstrument implements InstrumentsService_FindInstrument operation.
	//
	// Метод поиска инструмента.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/FindInstrument
	InstrumentsServiceFindInstrument(ctx context.Context, req *V1FindInstrumentRequest) (InstrumentsServiceFindInstrumentRes, error)
	// InstrumentsServiceFutureBy implements InstrumentsService_FutureBy operation.
	//
	// Метод получения фьючерса по его идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/FutureBy
	InstrumentsServiceFutureBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceFutureByRes, error)
	// InstrumentsServiceFutures implements InstrumentsService_Futures operation.
	//
	// Метод получения списка фьючерсов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Futures
	InstrumentsServiceFutures(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceFuturesRes, error)
	// InstrumentsServiceGetAccruedInterests implements InstrumentsService_GetAccruedInterests operation.
	//
	// Метод получения накопленного купонного дохода по
	// облигации.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAccruedInterests
	InstrumentsServiceGetAccruedInterests(ctx context.Context, req *V1GetAccruedInterestsRequest) (InstrumentsServiceGetAccruedInterestsRes, error)
	// InstrumentsServiceGetAssetBy implements InstrumentsService_GetAssetBy operation.
	//
	// Метод получения актива по его идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssetBy
	InstrumentsServiceGetAssetBy(ctx context.Context, req *V1AssetRequest) (InstrumentsServiceGetAssetByRes, error)
	// InstrumentsServiceGetAssets implements InstrumentsService_GetAssets operation.
	//
	// Метод получения списка активов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAssets
	InstrumentsServiceGetAssets(ctx context.Context, req *V1AssetsRequest) (InstrumentsServiceGetAssetsRes, error)
	// InstrumentsServiceGetBondCoupons implements InstrumentsService_GetBondCoupons operation.
	//
	// Метод получения графика выплат купонов по облигации.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBondCoupons
	InstrumentsServiceGetBondCoupons(ctx context.Context, req *V1GetBondCouponsRequest) (InstrumentsServiceGetBondCouponsRes, error)
	// InstrumentsServiceGetBrandBy implements InstrumentsService_GetBrandBy operation.
	//
	// Метод получения бренда по его идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrandBy
	InstrumentsServiceGetBrandBy(ctx context.Context, req *V1GetBrandRequest) (InstrumentsServiceGetBrandByRes, error)
	// InstrumentsServiceGetBrands implements InstrumentsService_GetBrands operation.
	//
	// Метод получения списка брендов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetBrands
	InstrumentsServiceGetBrands(ctx context.Context, req *V1GetBrandsRequest) (InstrumentsServiceGetBrandsRes, error)
	// InstrumentsServiceGetCountries implements InstrumentsService_GetCountries operation.
	//
	// Метод получения списка стран.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetCountries
	InstrumentsServiceGetCountries(ctx context.Context, req *V1GetCountriesRequest) (InstrumentsServiceGetCountriesRes, error)
	// InstrumentsServiceGetDividends implements InstrumentsService_GetDividends operation.
	//
	// Метод для получения событий выплаты дивидендов по
	// инструменту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetDividends
	InstrumentsServiceGetDividends(ctx context.Context, req *V1GetDividendsRequest) (InstrumentsServiceGetDividendsRes, error)
	// InstrumentsServiceGetFavorites implements InstrumentsService_GetFavorites operation.
	//
	// Метод получения списка избранных инструментов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFavorites
	InstrumentsServiceGetFavorites(ctx context.Context, req *V1GetFavoritesRequest) (InstrumentsServiceGetFavoritesRes, error)
	// InstrumentsServiceGetFuturesMargin implements InstrumentsService_GetFuturesMargin operation.
	//
	// Метод получения размера гарантийного обеспечения по
	// фьючерсам.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFuturesMargin
	InstrumentsServiceGetFuturesMargin(ctx context.Context, req *V1GetFuturesMarginRequest) (InstrumentsServiceGetFuturesMarginRes, error)
	// InstrumentsServiceGetInstrumentBy implements InstrumentsService_GetInstrumentBy operation.
	//
	// Метод получения основной информации об инструменте.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy
	InstrumentsServiceGetInstrumentBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceGetInstrumentByRes, error)
	// InstrumentsServiceOptionBy implements InstrumentsService_OptionBy operation.
	//
	// Метод получения опциона по его идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/OptionBy
	InstrumentsServiceOptionBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceOptionByRes, error)
	// InstrumentsServiceOptions implements InstrumentsService_Options operation.
	//
	// Метод получения списка опционов.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Options
	InstrumentsServiceOptions(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceOptionsRes, error)
	// InstrumentsServiceShareBy implements InstrumentsService_ShareBy operation.
	//
	// Метод получения акции по её идентификатору.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/ShareBy
	InstrumentsServiceShareBy(ctx context.Context, req *V1InstrumentRequest) (InstrumentsServiceShareByRes, error)
	// InstrumentsServiceShares implements InstrumentsService_Shares operation.
	//
	// Метод получения списка акций.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/Shares
	InstrumentsServiceShares(ctx context.Context, req *V1InstrumentsRequest) (InstrumentsServiceSharesRes, error)
	// InstrumentsServiceTradingSchedules implements InstrumentsService_TradingSchedules operation.
	//
	// Метод получения расписания торгов торговых площадок.
	//
	// POST /tinkoff.public.invest.api.contract.v1.InstrumentsService/TradingSchedules
	InstrumentsServiceTradingSchedules(ctx context.Context, req *V1TradingSchedulesRequest) (InstrumentsServiceTradingSchedulesRes, error)
	// MarketDataServiceGetCandles implements MarketDataService_GetCandles operation.
	//
	// Метод запроса исторических свечей по инструменту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles
	MarketDataServiceGetCandles(ctx context.Context, req *V1GetCandlesRequest) (MarketDataServiceGetCandlesRes, error)
	// MarketDataServiceGetClosePrices implements MarketDataService_GetClosePrices operation.
	//
	// Метод запроса цен закрытия торговой сессии по
	// инструментам.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetClosePrices
	MarketDataServiceGetClosePrices(ctx context.Context, req *V1GetClosePricesRequest) (MarketDataServiceGetClosePricesRes, error)
	// MarketDataServiceGetLastPrices implements MarketDataService_GetLastPrices operation.
	//
	// Метод запроса цен последних сделок по инструментам.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices
	MarketDataServiceGetLastPrices(ctx context.Context, req *V1GetLastPricesRequest) (MarketDataServiceGetLastPricesRes, error)
	// MarketDataServiceGetLastTrades implements MarketDataService_GetLastTrades operation.
	//
	// Метод запроса обезличенных сделок за последний час.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastTrades
	MarketDataServiceGetLastTrades(ctx context.Context, req *V1GetLastTradesRequest) (MarketDataServiceGetLastTradesRes, error)
	// MarketDataServiceGetOrderBook implements MarketDataService_GetOrderBook operation.
	//
	// Метод получения стакана по инструменту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook
	MarketDataServiceGetOrderBook(ctx context.Context, req *V1GetOrderBookRequest) (MarketDataServiceGetOrderBookRes, error)
	// MarketDataServiceGetTradingStatus implements MarketDataService_GetTradingStatus operation.
	//
	// Метод запроса статуса торгов по инструментам.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus
	MarketDataServiceGetTradingStatus(ctx context.Context, req *V1GetTradingStatusRequest) (MarketDataServiceGetTradingStatusRes, error)
	// MarketDataServiceGetTradingStatuses implements MarketDataService_GetTradingStatuses operation.
	//
	// Метод запроса статуса торгов по инструментам.
	//
	// POST /tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatuses
	MarketDataServiceGetTradingStatuses(ctx context.Context, req *V1GetTradingStatusesRequest) (MarketDataServiceGetTradingStatusesRes, error)
	// OperationsServiceGetBrokerReport implements OperationsService_GetBrokerReport operation.
	//
	// Метод получения брокерского отчёта.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetBrokerReport
	OperationsServiceGetBrokerReport(ctx context.Context, req *V1BrokerReportRequest) (OperationsServiceGetBrokerReportRes, error)
	// OperationsServiceGetDividendsForeignIssuer implements OperationsService_GetDividendsForeignIssuer operation.
	//
	// Метод получения отчёта "Справка о доходах за
	// пределами РФ".
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetDividendsForeignIssuer
	OperationsServiceGetDividendsForeignIssuer(ctx context.Context, req *V1GetDividendsForeignIssuerRequest) (OperationsServiceGetDividendsForeignIssuerRes, error)
	// OperationsServiceGetOperations implements OperationsService_GetOperations operation.
	//
	// Метод получения списка операций по счёту.При работе с
	// данным методом необходимо учитывать
	// [особенности взаимодействия](/investAPI/operations_problems) с
	// данным методом.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations
	OperationsServiceGetOperations(ctx context.Context, req *V1OperationsRequest) (OperationsServiceGetOperationsRes, error)
	// OperationsServiceGetOperationsByCursor implements OperationsService_GetOperationsByCursor operation.
	//
	// Метод получения списка операций по счёту с
	// пагинацией. При работе с данным методом необходимо
	// учитывать
	// [особенности взаимодействия](/investAPI/operations_problems) с
	// данным методом.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetOperationsByCursor
	OperationsServiceGetOperationsByCursor(ctx context.Context, req *V1GetOperationsByCursorRequest) (OperationsServiceGetOperationsByCursorRes, error)
	// OperationsServiceGetPortfolio implements OperationsService_GetPortfolio operation.
	//
	// Метод получения портфеля по счёту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio
	OperationsServiceGetPortfolio(ctx context.Context, req *V1PortfolioRequest) (OperationsServiceGetPortfolioRes, error)
	// OperationsServiceGetPositions implements OperationsService_GetPositions operation.
	//
	// Метод получения списка позиций по счёту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetPositions
	OperationsServiceGetPositions(ctx context.Context, req *V1PositionsRequest) (OperationsServiceGetPositionsRes, error)
	// OperationsServiceGetWithdrawLimits implements OperationsService_GetWithdrawLimits operation.
	//
	// Метод получения доступного остатка для вывода
	// средств.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OperationsService/GetWithdrawLimits
	OperationsServiceGetWithdrawLimits(ctx context.Context, req *V1WithdrawLimitsRequest) (OperationsServiceGetWithdrawLimitsRes, error)
	// OrdersServiceCancelOrder implements OrdersService_CancelOrder operation.
	//
	// Метод отмены биржевой заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OrdersService/CancelOrder
	OrdersServiceCancelOrder(ctx context.Context, req *V1CancelOrderRequest) (OrdersServiceCancelOrderRes, error)
	// OrdersServiceGetOrderState implements OrdersService_GetOrderState operation.
	//
	// Метод получения статуса торгового поручения.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderState
	OrdersServiceGetOrderState(ctx context.Context, req *V1GetOrderStateRequest) (OrdersServiceGetOrderStateRes, error)
	// OrdersServiceGetOrders implements OrdersService_GetOrders operation.
	//
	// Метод получения списка активных заявок по счёту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OrdersService/GetOrders
	OrdersServiceGetOrders(ctx context.Context, req *V1GetOrdersRequest) (OrdersServiceGetOrdersRes, error)
	// OrdersServicePostOrder implements OrdersService_PostOrder operation.
	//
	// Метод выставления заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OrdersService/PostOrder
	OrdersServicePostOrder(ctx context.Context, req *V1PostOrderRequest) (OrdersServicePostOrderRes, error)
	// OrdersServiceReplaceOrder implements OrdersService_ReplaceOrder operation.
	//
	// Метод изменения выставленной заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.OrdersService/ReplaceOrder
	OrdersServiceReplaceOrder(ctx context.Context, req *V1ReplaceOrderRequest) (OrdersServiceReplaceOrderRes, error)
	// SandboxServiceCancelSandboxOrder implements SandboxService_CancelSandboxOrder operation.
	//
	// Метод отмены торгового поручения в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/CancelSandboxOrder
	SandboxServiceCancelSandboxOrder(ctx context.Context, req *V1CancelOrderRequest) (SandboxServiceCancelSandboxOrderRes, error)
	// SandboxServiceCloseSandboxAccount implements SandboxService_CloseSandboxAccount operation.
	//
	// Метод закрытия счёта в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/CloseSandboxAccount
	SandboxServiceCloseSandboxAccount(ctx context.Context, req *V1CloseSandboxAccountRequest) (SandboxServiceCloseSandboxAccountRes, error)
	// SandboxServiceGetSandboxAccounts implements SandboxService_GetSandboxAccounts operation.
	//
	// Метод получения счетов в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxAccounts
	SandboxServiceGetSandboxAccounts(ctx context.Context, req *V1GetAccountsRequest) (SandboxServiceGetSandboxAccountsRes, error)
	// SandboxServiceGetSandboxOperations implements SandboxService_GetSandboxOperations operation.
	//
	// Метод получения операций в песочнице по номеру счёта.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperations
	SandboxServiceGetSandboxOperations(ctx context.Context, req *V1OperationsRequest) (SandboxServiceGetSandboxOperationsRes, error)
	// SandboxServiceGetSandboxOperationsByCursor implements SandboxService_GetSandboxOperationsByCursor operation.
	//
	// Метод получения операций в песочнице по номеру счета
	// с пагинацией.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperationsByCursor
	SandboxServiceGetSandboxOperationsByCursor(ctx context.Context, req *V1GetOperationsByCursorRequest) (SandboxServiceGetSandboxOperationsByCursorRes, error)
	// SandboxServiceGetSandboxOrderState implements SandboxService_GetSandboxOrderState operation.
	//
	// Метод получения статуса заявки в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrderState
	SandboxServiceGetSandboxOrderState(ctx context.Context, req *V1GetOrderStateRequest) (SandboxServiceGetSandboxOrderStateRes, error)
	// SandboxServiceGetSandboxOrders implements SandboxService_GetSandboxOrders operation.
	//
	// Метод получения списка активных заявок по счёту в
	// песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrders
	SandboxServiceGetSandboxOrders(ctx context.Context, req *V1GetOrdersRequest) (SandboxServiceGetSandboxOrdersRes, error)
	// SandboxServiceGetSandboxPortfolio implements SandboxService_GetSandboxPortfolio operation.
	//
	// Метод получения портфолио в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPortfolio
	SandboxServiceGetSandboxPortfolio(ctx context.Context, req *V1PortfolioRequest) (SandboxServiceGetSandboxPortfolioRes, error)
	// SandboxServiceGetSandboxPositions implements SandboxService_GetSandboxPositions operation.
	//
	// Метод получения позиций по виртуальному счёту
	// песочницы.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPositions
	SandboxServiceGetSandboxPositions(ctx context.Context, req *V1PositionsRequest) (SandboxServiceGetSandboxPositionsRes, error)
	// SandboxServiceGetSandboxWithdrawLimits implements SandboxService_GetSandboxWithdrawLimits operation.
	//
	// Метод получения доступного остатка для вывода
	// средств в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxWithdrawLimits
	SandboxServiceGetSandboxWithdrawLimits(ctx context.Context, req *V1WithdrawLimitsRequest) (SandboxServiceGetSandboxWithdrawLimitsRes, error)
	// SandboxServiceOpenSandboxAccount implements SandboxService_OpenSandboxAccount operation.
	//
	// Метод регистрации счёта в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/OpenSandboxAccount
	SandboxServiceOpenSandboxAccount(ctx context.Context, req *V1OpenSandboxAccountRequest) (SandboxServiceOpenSandboxAccountRes, error)
	// SandboxServicePostSandboxOrder implements SandboxService_PostSandboxOrder operation.
	//
	// Метод выставления торгового поручения в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxOrder
	SandboxServicePostSandboxOrder(ctx context.Context, req *V1PostOrderRequest) (SandboxServicePostSandboxOrderRes, error)
	// SandboxServiceReplaceSandboxOrder implements SandboxService_ReplaceSandboxOrder operation.
	//
	// Метод изменения выставленной заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/ReplaceSandboxOrder
	SandboxServiceReplaceSandboxOrder(ctx context.Context, req *V1ReplaceOrderRequest) (SandboxServiceReplaceSandboxOrderRes, error)
	// SandboxServiceSandboxPayIn implements SandboxService_SandboxPayIn operation.
	//
	// Метод пополнения счёта в песочнице.
	//
	// POST /tinkoff.public.invest.api.contract.v1.SandboxService/SandboxPayIn
	SandboxServiceSandboxPayIn(ctx context.Context, req *V1SandboxPayInRequest) (SandboxServiceSandboxPayInRes, error)
	// StopOrdersServiceCancelStopOrder implements StopOrdersService_CancelStopOrder operation.
	//
	// Метод отмены стоп-заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.StopOrdersService/CancelStopOrder
	StopOrdersServiceCancelStopOrder(ctx context.Context, req *V1CancelStopOrderRequest) (StopOrdersServiceCancelStopOrderRes, error)
	// StopOrdersServiceGetStopOrders implements StopOrdersService_GetStopOrders operation.
	//
	// Метод получения списка активных стоп заявок по счёту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.StopOrdersService/GetStopOrders
	StopOrdersServiceGetStopOrders(ctx context.Context, req *V1GetStopOrdersRequest) (StopOrdersServiceGetStopOrdersRes, error)
	// StopOrdersServicePostStopOrder implements StopOrdersService_PostStopOrder operation.
	//
	// Метод выставления стоп-заявки.
	//
	// POST /tinkoff.public.invest.api.contract.v1.StopOrdersService/PostStopOrder
	StopOrdersServicePostStopOrder(ctx context.Context, req *V1PostStopOrderRequest) (StopOrdersServicePostStopOrderRes, error)
	// UsersServiceGetAccounts implements UsersService_GetAccounts operation.
	//
	// Метод получения счетов пользователя.
	//
	// POST /tinkoff.public.invest.api.contract.v1.UsersService/GetAccounts
	UsersServiceGetAccounts(ctx context.Context, req *V1GetAccountsRequest) (UsersServiceGetAccountsRes, error)
	// UsersServiceGetInfo implements UsersService_GetInfo operation.
	//
	// Метод получения информации о пользователе.
	//
	// POST /tinkoff.public.invest.api.contract.v1.UsersService/GetInfo
	UsersServiceGetInfo(ctx context.Context, req *V1GetInfoRequest) (UsersServiceGetInfoRes, error)
	// UsersServiceGetMarginAttributes implements UsersService_GetMarginAttributes operation.
	//
	// Расчёт маржинальных показателей по счёту.
	//
	// POST /tinkoff.public.invest.api.contract.v1.UsersService/GetMarginAttributes
	UsersServiceGetMarginAttributes(ctx context.Context, req *V1GetMarginAttributesRequest) (UsersServiceGetMarginAttributesRes, error)
	// UsersServiceGetUserTariff implements UsersService_GetUserTariff operation.
	//
	// Запрос тарифа пользователя.
	//
	// POST /tinkoff.public.invest.api.contract.v1.UsersService/GetUserTariff
	UsersServiceGetUserTariff(ctx context.Context, req *V1GetUserTariffRequest) (UsersServiceGetUserTariffRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
